.TH _PRINTF 3 "January 2024" "Version 1.0" "User Commands"

.SH NAME
_printf \- formatted output conversion

.SH SYNOPSIS
.B #include <stdio.h>
.I int _printf(const char *format, ...);

.SH DESCRIPTION
The \fB_printf\fR function sends formatted output to stdout according to the format string \fIformat\fR. The function formats and prints its arguments under control of the \fIformat\fR string.

.SH RETURN VALUE
Upon successful completion, the \fB_printf\fR function returns the number of characters printed (excluding the null byte used to end output to strings).

If an output error is encountered, the function returns a negative value.

.SH EXAMPLES
The following example demonstrates the usage of \fB_printf\fR:
.nf
.PP
#include <stdio.h>
#include "main.h"

int main() {
    int num = 10;
    _printf("The value of num is: %d\n", num);
    return 0;
}
.fi

.SH SEE ALSO
fprintf(3), sprintf(3), snprintf(3), printf(3)

.SH AUTHOR
Written by [John, Jose, Abimael].

.SH BUGS
Report bugs to 9043@holbertonstudents.com.

